apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
    server: https://IIII9999DDDD.gr7.us-east-1.eks.amazonaws.com
  name: eks-billing-dev
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
    server: https://JJJJ0000EEEE.gr7.us-east-1.eks.amazonaws.com
  name: eks-billing-qa
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
    server: https://KKKK1111FFFF.gr7.us-east-1.eks.amazonaws.com
  name: eks-infra-dev
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
    server: https://LLLL2222AAAA.gr7.us-east-1.eks.amazonaws.com
  name: eks-infra-pdn
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
    server: https://DDDD4444EEEE.gr7.us-east-1.eks.amazonaws.com
  name: eks-orders-dev
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
    server: https://FFFF6666AAAA.gr7.us-east-1.eks.amazonaws.com
  name: eks-orders-pdn
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
    server: https://EEEE5555FFFF.gr7.us-east-1.eks.amazonaws.com
  name: eks-orders-qa
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
    server: https://AAAA1111BBBB.gr7.us-east-1.eks.amazonaws.com
  name: eks-payments-dev
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
    server: https://CCCC3333DDDD.gr7.us-east-1.eks.amazonaws.com
  name: eks-payments-pdn
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
    server: https://BBBB2222CCCC.gr7.us-east-1.eks.amazonaws.com
  name: eks-payments-qa
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
    server: https://GGGG7777BBBB.gr7.us-east-1.eks.amazonaws.com
  name: eks-platform-dev
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
    server: https://HHHH8888CCCC.gr7.us-east-1.eks.amazonaws.com
  name: eks-platform-qa
contexts:
- context:
    cluster: eks-billing-dev
    namespace: default
    user: demo-user
  name: eks-billing-dev
- context:
    cluster: eks-billing-qa
    namespace: default
    user: demo-user
  name: eks-billing-qa
- context:
    cluster: eks-infra-dev
    namespace: default
    user: demo-user
  name: eks-infra-dev
- context:
    cluster: eks-infra-pdn
    namespace: default
    user: demo-user
  name: eks-infra-pdn
- context:
    cluster: eks-orders-dev
    namespace: default
    user: demo-user
  name: eks-orders-dev
- context:
    cluster: eks-orders-pdn
    namespace: default
    user: demo-user
  name: eks-orders-pdn
- context:
    cluster: eks-orders-qa
    namespace: default
    user: demo-user
  name: eks-orders-qa
- context:
    cluster: eks-payments-dev
    namespace: default
    user: demo-user
  name: eks-payments-dev
- context:
    cluster: eks-payments-pdn
    namespace: default
    user: demo-user
  name: eks-payments-pdn
- context:
    cluster: eks-payments-qa
    namespace: default
    user: demo-user
  name: eks-payments-qa
- context:
    cluster: eks-platform-dev
    namespace: default
    user: demo-user
  name: eks-platform-dev
- context:
    cluster: eks-platform-qa
    namespace: default
    user: demo-user
  name: eks-platform-qa
current-context: eks-payments-pdn
kind: Config
users:
- name: demo-user
  user:
    token: demo-token-not-real
